In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('anime.csv')

In [24]:
df.head(5)

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
df.loc[2]

Rank                                                     3
Title    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
Score                                                 9.06
Name: 2, dtype: object

In [6]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

In [121]:
def extract_episode(text):
    check=False
    data=""
    for i in text:
        if i==")":
            check=False
            return data 
        if check ==True:
            data+=i             
        if i=='(':
            check=True

In [ ]:
df['Title'].apply(extract_episode)

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: str

In [161]:
df['Episodes']=df['Title'].apply(extract_episode)
df.head()

,Rank,Title,Score,Total time,total_months,Episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,16,64 eps
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,6,24 eps
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,3,13 eps
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,12,51 eps
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,4,10 eps

In [191]:
df['Episodes']=df['Episodes'].str.replace(" eps","")
df['Episodes']=df['Episodes'].astype(int)
df.head()

,Rank,Title,Score,Total time,total_months,Episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,16,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,6,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,3,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,12,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,4,10

Make new column of Total time

In [78]:
def extract_date(text):
    check=False
    data=""
    for i in range(len(text)):
        if text[i]==')':
            for j in range(i+1,i+20):
                data+= text[j]
            return data

In [154]:
df['Total time']=df['Title'].apply(extract_date)
df.head()

,Rank,Title,Score,Total time,total_months,Episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,16,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,6,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,3,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,12,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,4,10

Make New Column of total month

In [108]:


def total_months(s, inclusive=True):
    try:
        start, end = [x.strip() for x in s.split('-')]
        start = pd.to_datetime(start, format='%b %Y')
        # handle "Present"/"Current" as today's date
        if end.lower() in ('present', 'current', 'till date'):
            end = pd.Timestamp.today()
        else:
            end = pd.to_datetime(end, format='%b %Y')
        months = (end.year - start.year) * 12 + (end.month - start.month)
        return months + 1 if inclusive else months
    except Exception:
        return None  # malformed or missing values

In [153]:
df['total_months'] = df['Total time'].apply(total_months)
df.head()

,Rank,Title,Score,Total time,total_months,Episodes
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,Apr 2009 - Jul 2010,16,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,Apr 2011 - Sep 2011,6,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,Oct 2022 - Dec 2022,3,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,Apr 2015 - Mar 2016,12,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,Apr 2019 - Jul 2019,4,10

Which Anime Have Highest score

In [148]:
df[df['Score']==df['Score'].max()]["Title"]

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

5 top scoring Anime

In [111]:
#our data frame is shorte
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [190]:
print(df['Episodes'].dtype)

str

Which Anime have highest Anime count

In [192]:
df[df['Episodes']==df['Episodes'].max()]

,Rank,Title,Score,Total time,total_months,Episodes
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,Apr 2006 - Mar 2010,48,201

1.Anime with Top 5 Episode Count
2.Which is the largest running anime