In [4]:
import pandas as pd 
import numpy as np

## Creating DataFrame

no of element in each column will be same other wise you will get value error ex:- in Name, Age,  City

In [5]:
data_by_column = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30 , 41],
    "City": ["New York", "London", "Paris"]
}
data_by_row = [
    {"Name": "Alice", "Age": 25, "City": "New York"},
    {"Name": "Bob", "Age": 30, "City": "London"},
    {"Name": "Charlie", "Age": 35, "City": "Paris"}
]
lable=["a","b","c"]

In [6]:
pd.DataFrame(data_by_column,lable)

      Name  Age      City
a    Alice   25  New York
b      Bob   30    London
c  Charlie   41     Paris

In [19]:
pd.DataFrame(data_by_row,index=lable)

       Name  Age      City
10    Alice   25  New York
20      Bob   30    London
30  Charlie   35     Paris

In [16]:
data_list = [
    ["Alice", 25, "New York"],
    ["Bob", 30, "London"],
    ["Charlie", 35, "Paris"]
]

##
names = ["Alice", "Bob", "Charlie"]
ages = [25, 30, 35]
cities = ["New York", "London", "Paris"]
a=list(zip(names, ages, cities))

In [17]:
pd.DataFrame(data_list)

         0   1         2
0    Alice  25  New York
1      Bob  30    London
2  Charlie  35     Paris

In [18]:
lable=[10,20,30]
col=["names","age","cities"]
df1=pd.DataFrame(data_list, columns=col, index=lable)

In [19]:
df1

      names  age    cities
10    Alice   25  New York
20      Bob   30    London
30  Charlie   35     Paris

## Selection and indexing of column

In [20]:
df1

      names  age    cities
10    Alice   25  New York
20      Bob   30    London
30  Charlie   35     Paris

Targetting a Column

In [21]:
df1["names"]   #dont try to ues index inside the [],it work with column name

10      Alice
20        Bob
30    Charlie
Name: names, dtype: str

Targeting Multiple column

In [22]:
df1[["names","age"]]

      names  age
10    Alice   25
20      Bob   30
30  Charlie   35

## Creating New Column

In [34]:
df1["Designation"]=["doctor","engg.","doctor"]
df1

      names  age    cities Designation
10    Alice   25  New York      doctor
20      Bob   30    London       engg.
30  Charlie   35     Paris      doctor

## Removing Columns

In [ ]:
df1.drop("Designation", axis=1, inplace=True, errors="ignore")   # use inplace=TRUE     to do change in acctual data set

In [35]:
df1.drop(["Designation","cities"],axis=1)
                         #1 is for axis=y , 0 for axis =x

      names  age
10    Alice   25
20      Bob   30
30  Charlie   35

both single and multiple rows can be drop using drop

In [37]:
df1.drop(10,axis=0)

      names  age  cities Designation
20      Bob   30  London       engg.
30  Charlie   35   Paris      doctor

## Selecting Row

loc work on row name

In [38]:
df1.loc[10]

names             Alice
age                  25
cities         New York
Designation      doctor
Name: 10, dtype: object

In [39]:
df1.loc[[10,20]]

    names  age    cities Designation
10  Alice   25  New York      doctor
20    Bob   30    London       engg.

SelectingSubset of row And Column

In [40]:
df1.loc[[10,20]][["names","age"]]

    names  age
10  Alice   25
20    Bob   30

iloc work on row index

In [43]:
df1.iloc[0]

names             Alice
age                  25
cities         New York
Designation      doctor
Name: 10, dtype: object

# Conditional selection

In [44]:
df1

      names  age    cities Designation
10    Alice   25  New York      doctor
20      Bob   30    London       engg.
30  Charlie   35     Paris      doctor

In [46]:
#to select the people having age grater than 25
df1[df1["age"]>25]

      names  age  cities Designation
20      Bob   30  London       engg.
30  Charlie   35   Paris      doctor

In [50]:
#to select people with age more than 30 and city must be paris 
df1[(df1["age"] > 30) & (df1["cities"] == "Paris")]

      names  age cities Designation
30  Charlie   35  Paris      doctor