In [1]:
import pandas as pd
import numpy as np

# GroupBy

In [4]:
data = {
    "date": ["2026-09-25", "2026-09-25", "2026-09-26", "2026-09-26", "2026-09-27", "2026-09-27"],
    "store": ["Store A", "Store B", "Store A", "Store B", "Store A", "Store B"],
    "category": ["Electronics", "Clothing", "Electronics", "Electronics", "Clothing", "Clothing"],
    "sales": [1200.50, 450.00, 800.00, 1500.00, 300.00, 650.75],
    "quantity": [3, 15, 2, 4, 10, 22]
}
df=pd.DataFrame(data)

In [5]:
df

         date    store     category    sales  quantity
0  2026-09-25  Store A  Electronics  1200.50         3
1  2026-09-25  Store B     Clothing   450.00        15
2  2026-09-26  Store A  Electronics   800.00         2
3  2026-09-26  Store B  Electronics  1500.00         4
4  2026-09-27  Store A     Clothing   300.00        10
5  2026-09-27  Store B     Clothing   650.75        22

Group by Category and calculate the sum of sales

In [8]:
c=df.groupby("category") #igroupby will generate object , that you can't access in general way
for i,v in c:
    print(i)
    print(v)

Clothing
         date    store  category   sales  quantity
1  2026-09-25  Store B  Clothing  450.00        15
4  2026-09-27  Store A  Clothing  300.00        10
5  2026-09-27  Store B  Clothing  650.75        22
Electronics
         date    store     category   sales  quantity
0  2026-09-25  Store A  Electronics  1200.5         3
2  2026-09-26  Store A  Electronics   800.0         2
3  2026-09-26  Store B  Electronics  1500.0         4

In [17]:
df.groupby('category')['sales'].sum()

category
Clothing       1400.75
Electronics    3500.50
Name: sales, dtype: float64

In [18]:
df.groupby('category')[['sales','quantity']].sum()

               sales  quantity
category
Clothing     1400.75        47
Electronics  3500.50         9

In [10]:
#Group by store and do sum of sales
df.groupby("store")['sales'].sum()

store
Store A    2300.50
Store B    2600.75
Name: sales, dtype: float64

In [11]:
#groupby Multiple column
#group by category and store 
df.groupby(["category","store"])['sales'].sum()

category     store
Clothing     Store A     300.00
             Store B    1100.75
Electronics  Store A    2000.50
             Store B    1500.00
Name: sales, dtype: float64

In [19]:
df.groupby(["category","store"])[['sales','quantity']].sum()

                       sales  quantity
category    store
Clothing    Store A   300.00        10
            Store B  1100.75        37
Electronics Store A  2000.50         5
            Store B  1500.00         4

In [ ]:
df.groupby(["category","store"])[['sales','quantity']].agg(['sum','mean','max','min'])

                       sales                            quantity
                         sum      mean      max     min      sum  mean max min
category    store
Clothing    Store A   300.00   300.000   300.00   300.0       10  10.0  10  10
            Store B  1100.75   550.375   650.75   450.0       37  18.5  22  15
Electronics Store A  2000.50  1000.250  1200.50   800.0        5   2.5   3   2
            Store B  1500.00  1500.000  1500.00  1500.0        4   4.0   4   4

# Aggregation

min(), max(), count(), mean(), median(), mod(), standarddeviaion(), Varience()   they are basic aggriation function


Agg function will be applyed on column

In [ ]:
df['sales'].mean()   # you cna place other agg function in place of mean()

np.float64(816.875)

In [15]:
df['sales'].agg(['sum','mean','median','max','min']) #used to apply multipple function at same time

sum       4901.250
mean       816.875
median     725.375
max       1500.000
min        300.000
Name: sales, dtype: float64