In [2]:
import pandas as pd
import numpy as np

# MErging 2 Data frame


1. pd.merge() 

(Database-Style Joining)Use merge when you want to combine DataFrames based on common values in specific columns, exactly like an SQL JOIN.

Best for: Connecting tables with shared ID columns (e.g., matching employee_id in a names table to employee_id in a salaries table).

Flexibility: Very high. Column names do not have to match exactly between tables (left_on and right_on handle mismatches).

In [3]:
data1 = {
    "employee_id": [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "David"]
}
data2 = {
    "employee_id": [101, 102, 103, 105],
    "salary": [50000, 60000, 55000, 70000]
}

In [4]:
a=pd.DataFrame(data1)
print(a)
b=pd.DataFrame(data2)
print(b)

   employee_id     name
0          101    Alice
1          102      Bob
2          103  Charlie
3          104    David
   employee_id  salary
0          101   50000
1          102   60000
2          103   55000
3          105   70000

In [ ]:
pd.merge(a,b,on='employee_id') # merge always need one common colum between table to be merge

   employee_id     name  salary
0          101    Alice   50000
1          102      Bob   60000
2          103  Charlie   55000

In [6]:
pd.merge(a,b,on="employee_id",how="inner") #it will only merge those column that have common value in common column

   employee_id     name  salary
0          101    Alice   50000
1          102      Bob   60000
2          103  Charlie   55000

In [ ]:
pd.merge(a,b,on="employee_id",how="outer") # it will merge every row and fill null where values are not avaliable

   employee_id     name   salary
0          101    Alice  50000.0
1          102      Bob  60000.0
2          103  Charlie  55000.0
3          104    David      NaN
4          105      NaN  70000.0

In [ ]:
pd.merge(a,b,on="employee_id",how="left") #it will merge all rows of left side table

   employee_id     name   salary
0          101    Alice  50000.0
1          102      Bob  60000.0
2          103  Charlie  55000.0
3          104    David      NaN

In [ ]:
pd.merge(a,b,on="employee_id",how="right")  #it will merge all rows from right side

   employee_id     name  salary
0          101    Alice   50000
1          102      Bob   60000
2          103  Charlie   55000
3          105      NaN   70000

# Conctination of 2 Dataframe

* pd.concat()  

(Stacking Data)Use concat when you want to glue or stack multiple DataFrames together along an axis (either on top of each other or side-by-side).

Best for: Combining data that has been split up (e.g., stacking monthly sales files like January, February, and March into one yearly dataset).

Flexibility: Can combine more than two DataFrames at once.

In [12]:
data_jan = {
    "product": ["Laptop", "Mouse", "Keyboard"],
    "units_sold": [50, 120, 80]
}
data_feb = {
    "product": ["Laptop", "Mouse", "Monitor"],
    "units_sold": [45, 110, 35]
}
sales1=pd.DataFrame(data_jan)
sales2=pd.DataFrame(data_feb)

In [13]:
sales1

    product  units_sold
0    Laptop          50
1     Mouse         120
2  Keyboard          80

In [14]:
sales2

   product  units_sold
0   Laptop          45
1    Mouse         110
2  Monitor          35

In [15]:
pd.concat([sales1,sales1])

    product  units_sold
0    Laptop          50
1     Mouse         120
2  Keyboard          80
0    Laptop          50
1     Mouse         120
2  Keyboard          80

In [16]:
pd.concat([sales1,sales2],axis=1)

    product  units_sold  product  units_sold
0    Laptop          50   Laptop          45
1     Mouse         120    Mouse         110
2  Keyboard          80  Monitor          35

# Joining 2 DataFrame

3. DataFrame.join() (Index-Based Combining) 

Use join as a convenient shorthand to combine DataFrames based on their row indexes instead of their columns

Best for: Fast lookup combinations where your unique identifiers are already set as the DataFrame index.

Flexibility: By default, it looks strictly at row indexes, though you can configure it to join a left column onto a right index.

In [17]:
df_users = pd.DataFrame(
    {"name": ["Alice", "Bob", "Charlie"]},
    index=[101, 102, 103]
)
df_activity = pd.DataFrame(
    {"login_count": [12, 45, 8]},
    index=[101, 102, 104]
)
df1=pd.DataFrame(df_users)
df2=pd.DataFrame(df_activity)

In [21]:
df1

        name
101    Alice
102      Bob
103  Charlie

In [22]:
df2

     login_count
101           12
102           45
104            8

In [ ]:
df1.join(df2) # left join

        name  login_count
101    Alice         12.0
102      Bob         45.0
103  Charlie          NaN

In [27]:
df1.join(df2,how='left')

        name  login_count
101    Alice         12.0
102      Bob         45.0
103  Charlie          NaN

In [28]:
df1.join(df2,how='right')

      name  login_count
101  Alice           12
102    Bob           45
104    NaN            8

In [26]:
df1.join(df2,how='inner')

      name  login_count
101  Alice           12
102    Bob           45

In [20]:
df1.join(df2,how='outer')

        name  login_count
101    Alice         12.0
102      Bob         45.0
103  Charlie          NaN
104      NaN          8.0