In [1]:
import numpy as np
import pandas as pd

# Finding Missing Data

In [11]:
data={
    'A':[1,2,3,np.nan,5],
    'b':[np.nan,2,3,np.nan,5],
    'c':[1,np.nan,3,4,5],
    'd':[1,2,3,4,5]
}
df=pd.DataFrame(data)

In [31]:
df

     A    b    c  d
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  3.0  3.0  3.0  3
3  NaN  NaN  4.0  4
4  5.0  5.0  5.0  5

In [13]:
df.isna()

       A      b      c      d
0  False   True  False  False
1  False  False   True  False
2  False  False  False  False
3   True   True  False  False
4  False  False  False  False

In [14]:
df.isna().sum() #Null Value in each columns

A    1
b    2
c    1
d    0
dtype: int64

In [15]:
df.isna().any()

A     True
b     True
c     True
d    False
dtype: bool

# Removing Missing Data

In [16]:
df

     A    b    c  d
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  3.0  3.0  3.0  3
3  NaN  NaN  4.0  4
4  5.0  5.0  5.0  5

In [ ]:
df.dropna() #drop the row contaning null value in any columns

     A    b    c  d
2  3.0  3.0  3.0  3
4  5.0  5.0  5.0  5

In [ ]:
df.dropna(thresh=3) # it will remove every row that not contaning at least 3 not null values

     A    b    c  d
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  3.0  3.0  3.0  3
4  5.0  5.0  5.0  5

In [34]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, b, c, d]
Index: []

# Filling The missing data

In [35]:
df

     A    b    c  d
0  1.0  NaN  1.0  1
1  2.0  2.0  NaN  2
2  3.0  3.0  3.0  3
3  NaN  NaN  4.0  4
4  5.0  5.0  5.0  5

In [36]:
df.fillna(0)

     A    b    c  d
0  1.0  0.0  1.0  1
1  2.0  2.0  0.0  2
2  3.0  3.0  3.0  3
3  0.0  0.0  4.0  4
4  5.0  5.0  5.0  5

In [37]:
values={'A':10,'b':20,'c':30,'d':40}
df.fillna(value=values)

      A     b     c  d
0   1.0  20.0   1.0  1
1   2.0   2.0  30.0  2
2   3.0   3.0   3.0  3
3  10.0  20.0   4.0  4
4   5.0   5.0   5.0  5

In [38]:
df.fillna(df.mean())

      A         b     c  d
0  1.00  3.333333  1.00  1
1  2.00  2.000000  3.25  2
2  3.00  3.000000  3.00  3
3  2.75  3.333333  4.00  4
4  5.00  5.000000  5.00  5