In [1]:
import pandas as pd
import numpy as np

In [2]:


# Set seed for reproducible random data
np.random.seed(42)

# Generate 100 rows of categorical data matching typical tutorial sets
n_rows = 100
dates = pd.date_range(start="2026-01-01", periods=4, freq="D").strftime("%Y-%m-%d").tolist() * 25
regions = np.random.choice(["North", "South", "East", "West"], size=n_rows)
products = np.random.choice(["Laptop", "Smartphone", "Tablet", "Headphones"], size=n_rows)
sales = np.random.randint(100, 1500, size=n_rows)
quantity = np.random.randint(1, 10, size=n_rows)

# Create the data frame
df = pd.DataFrame({
    "Date": dates,
    "Region": regions,
    "Product": products,
    "Sales": sales,
    "Quantity": quantity
})

# Display the first 10 rows
print("--- Raw DataFrame (First 10 Rows) ---")
print(df.head(10))

--- Raw DataFrame (First 10 Rows) ---
         Date Region     Product  Sales  Quantity
0  2026-01-01   East      Tablet    963         3
1  2026-01-02   West  Smartphone    842         7
2  2026-01-03  North  Smartphone   1364         9
3  2026-01-04   East  Headphones    663         4
4  2026-01-01   East  Smartphone   1120         1
5  2026-01-02   West  Smartphone    195         2
6  2026-01-03  North  Smartphone    584         1
7  2026-01-04  North  Headphones    330         5
8  2026-01-01   East  Smartphone    848         5
9  2026-01-02  South      Tablet   1294         7

In [4]:
df

          Date Region     Product  Sales  Quantity
0   2026-01-01   East      Tablet    963         3
1   2026-01-02   West  Smartphone    842         7
2   2026-01-03  North  Smartphone   1364         9
3   2026-01-04   East  Headphones    663         4
4   2026-01-01   East  Smartphone   1120         1
..         ...    ...         ...    ...       ...
95  2026-01-04  South  Smartphone    971         1
96  2026-01-01  South  Smartphone    740         8
97  2026-01-02   West  Headphones    572         1
98  2026-01-03  South      Laptop    250         9
99  2026-01-04  North      Tablet   1421         6

[100 rows x 5 columns]

# Pivote Table

A pivot table is used to transform messy, row-by-row data into a clean, summarized summary table without changing originalm table

used in creation of heatmap

In [ ]:

pd.pivot_table(df,values='Sales',index='Region',columns='Product') # by default povit table give mean for ex
#677.5 is mean of hadephone in east region

Product   Headphones      Laptop  Smartphone  Tablet
Region
East      677.500000  919.181818     888.250  1178.6
North     808.000000  712.000000    1192.000  1007.0
South    1037.333333  925.000000     828.125   932.2
West      970.857143  987.750000     534.250   759.4

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product', aggfunc='median')

Product  Headphones  Laptop  Smartphone  Tablet
Region
East          651.5   863.0       984.0  1176.0
North         851.0   768.0      1356.0  1348.0
South        1066.0  1028.0       855.5   798.0
West         1236.0   910.0       550.0   708.0

In [ ]:
pivot=pd.pivot_table(df,values=['Sales','Quantity'],index='Region',columns='Product') #values must be quantative(Numerical) other wiase agg function will fail
pivot

          Quantity                                       Sales              \
Product Headphones    Laptop Smartphone    Tablet   Headphones      Laptop
Region
East      5.000000  3.818182       3.00  4.600000   677.500000  919.181818
North     4.000000  7.000000       4.25  4.600000   808.000000  712.000000
South     5.166667  4.285714       4.75  3.800000  1037.333333  925.000000
West      5.142857  4.250000       5.25  4.933333   970.857143  987.750000


Product Smartphone  Tablet
Region
East       888.250  1178.6
North     1192.000  1007.0
South      828.125   932.2
West       534.250   759.4

# CrossTab

In [18]:
pd.crosstab(df['Region'],df['Product'])    #it just provide the no ex- 4 headphone in east region

Product  Headphones  Laptop  Smartphone  Tablet
Region
East              4      11           4       5
North             7       4           4       5
South             6       7           8       5
West              7       4           4      15